services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    env_file:
      - ../.env
    user: "${FILEBROWSER_USER}:${FILEBROWSER_GROUP}"
    ports:
      - '8083:80'
    volumes:
      - /:/srv
      - ./data:/database
    restart: unless-stopped
    networks:
      - raspberry-net

networks:
  raspberry-net:
    external: true
